apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: cahbo
  name: cahbo
spec:
  ports:
  - name: "8054"
    port: 8054
    targetPort: 7054
  selector:
    io.kompose.service: cahbo
status:
  loadBalancer: {}
