apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: cli
  name: cli
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cli
    spec:
      containers:
      - env:
        #- name: CORE_LOGGING_LEVEL
        #  value: DEBUG
        #- name: CORE_PEER_ADDRESS
        #  value: peer0-netflix-myapp-com:7051
        #- name: CORE_PEER_ID
        #  value: cli
        - name: CORE_PEER_LOCALMSPID
          value: netflixMSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/netflix.myapp.com/users/Admin@netflix.myapp.com/msp
        - name: CORE_PEER_TLS_CERT_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/netflix.myapp.com/peers/peer0.netflix.myapp.com/tls/server.crt
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_KEY_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/netflix.myapp.com/peers/peer0.netflix.myapp.com/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/netflix.myapp.com/peers/peer0.netflix.myapp.com/tls/ca.crt
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: GOPATH
          value: /opt/gopath
        - name: CORE_VM_DOCKER_HOSTCONFIG_DNS
          value: 10.3.240.10
        image: hyperledger/fabric-tools
        name: cli
        resources: {}
        tty: true
        volumeMounts:
        - name: my-pvc-nfs
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
          subPath: chaincode
        - name: my-pvc-nfs
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
          #subPath: peerOrganizations
        - name: my-pvc-nfs
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
          subPath: scripts
        - name: my-pvc-nfs
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
          subPath: channel-artifacts
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      restartPolicy: Always
      volumes:
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: nfs
status: {}
