apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: orderer-myapp-com
  name: orderer-myapp-com
spec:
  type: NodePort
  ports:
  - name: "7050"
    port: 7050
    targetPort: 7050
    nodePort: 30050
  selector:
    io.kompose.service: orderer-myapp-com
