apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: peer0-hbo-myapp-com
  name: peer0-hbo-myapp-com
spec:
  type: NodePort
  ports:
    - name: externale-listen-endpoint
      protocol: TCP
      port: 7051
      targetPort: 7051
      nodePort: 30051

    - name: chaincode-listen
      protocol: TCP
      port: 7052
      targetPort: 7052
      nodePort: 30052

#  - name: "8051"
#    port: 8051
#    targetPort: 7051
#  - name: "8052"
#    port: 8052
#    targetPort: 7052
#  - name: "8053"
#    port: 8053
#    targetPort: 7053
  selector:
    io.kompose.service: peer0-hbo-myapp-com
