apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: orderer-myapp-com
  name: orderer-myapp-com
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: orderer-myapp-com
    spec:
      containers:
      - args:
        - orderer
        env:
        - name: ORDERER_GENERAL_GENESISFILE
          value: /var/hyperledger/orderer/orderer.genesis.block
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /var/hyperledger/orderer/msp
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_LOGLEVEL
          value: debug
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /var/hyperledger/orderer/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /var/hyperledger/orderer/tls/server.key 
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: '[/var/hyperledger/orderer/tls/ca.crt]'
        - name: CORE_VM_DOCKER_HOSTCONFIG_DNS
          value: 10.3.240.10
        image: hyperledger/fabric-orderer
        name: orderer-myapp-com
        ports:
        - containerPort: 7050
        resources: {}
        volumeMounts:
        - name: my-pvc-nfs
          mountPath: /var/hyperledger/orderer/msp 
          subPath: ordererOrganizations/myapp.com/orderers/orderer.myapp.com/msp
        - mountPath: /var/hyperledger/orderer/orderer.genesis.block
          name: my-pvc-nfs
          subPath: genesis.block 
        - mountPath: /var/hyperledger/orderer/tls
          name: my-pvc-nfs
          subPath: ordererOrganizations/myapp.com/orderers/orderer.myapp.com/tls
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric
      restartPolicy: Always
      volumes:
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: nfs
        
status: {}
